name: Dump
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # ローカルアクション呼び出し前にチェックアウト
      - uses: ./.github/actions/dump/   # ローカルアクションの呼び出し
        id: dump    # 出力地参照のためステップIDを定義
        with:
          enable-context: 'true'    # 入力パラメータの設定
      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.cump.outputs.dumped-date }}   # アクションの出力値を参照
